name : Testing SonarQube

on:
  pull_request:
    branches: [feature-1]

jobs:
  Testing_sonarqube_report:
    name: Testing sonarqube report on feature branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}